name: leaderboard_repository
description: A repository to access leaderboard data in Firebase Cloud Firestore.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:  
  dio: ^5.7.0
  equatable: ^2.0.5 
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
